#!/bin/bash
# shellcheck disable=SC2046
# shellcheck disable=SC2155
#
# sqs-functions

queues() {
  local queue_name_prefix=$(__bma_read_inputs $@)
  local filters=$(__bma_read_filters $@)

  aws sqs list-queues \
    $([[ -n ${queue_name_prefix} ]] && echo --queue-name-prefix ${queue_name_prefix}) \
    --query "QueueUrls[]" --output text |
    tr '\t' '\n' |
    grep -iE -- "$filters" |
    sort -b
}

queue-attributes() {
  local queue_urls="$(__bma_read_inputs $@)"
  [[ -z "$queue_urls" ]] && __bma_usage "queue-url" && return 1

  output=$(for queue_url in $queue_urls; do
    aws sqs get-queue-attributes \
      $([[ -n ${queue_url} ]] && echo --queue-url ${queue_url}) \
      --attribute-names All \
      --output json
  done)
  echo "$output" | jq -s
}

queue-purge() {
  local queue_urls="$(__bma_read_inputs $@)"
  [[ -z "$queue_urls" ]] && __bma_usage "queue-url [queue-url]" && return 1

  echo "You are about to purge the following queues:"
  queue-attributes "${queue_urls}"
  [ -t 0 ] || exec </dev/tty # reattach keyboard to STDIN
  local regex_yes="^[Yy]$"
  read -p "Are you sure you want to continue? " -n 1 -r
  echo
  if [[ $REPLY =~ $regex_yes ]]; then
    for queue_url in ${queue_urls}; do
      aws sqs purge-queue --queue-url "$queue_url"
    done
  fi
}
